/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * AUTHOR: SOFIA NOVAK
 * DATE: 26/09/17
 */
package figurasgeometricas2d;

import java.awt.Color;

/**
 *
 * @author 
 */
public class Ventana2 extends javax.swing.JFrame {
    //Atributo
    private  Circulo circulo1; 
    private Cuadrilatero cuadrado;
    private Rectangulo rectangulo;
    private TrianguloRectangulo triangulo;
    
    
    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
        circulo1= new Circulo();
        cuadrado=new Cuadrilatero();
        rectangulo=new Rectangulo();
        triangulo =new TrianguloRectangulo();
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        circulo = new javax.swing.JPanel();
        campoRadio = new javax.swing.JTextField();
        calcularCirculo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonCapturaRadio = new javax.swing.JButton();
        Rectangulo = new javax.swing.JPanel();
        campoBaseRect = new javax.swing.JTextField();
        campoAlturaRect = new javax.swing.JTextField();
        calcularRectagulo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ingresarValores = new javax.swing.JButton();
        cuadrilatero = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoBaseCuad = new javax.swing.JTextField();
        campoAlturaCuad = new javax.swing.JTextField();
        ingresarValorCuad = new javax.swing.JButton();
        calcularCuad = new javax.swing.JButton();
        Triangulos = new javax.swing.JPanel();
        campoCatMay = new javax.swing.JTextField();
        campoCatMen = new javax.swing.JTextField();
        calcularTriangulo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoHipot = new javax.swing.JTextField();
        ingresarValorTriang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoResultado = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoRadio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoRadioFocusGained(evt);
            }
        });
        campoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRadioActionPerformed(evt);
            }
        });

        calcularCirculo.setText("Calcular");
        calcularCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularCirculoActionPerformed(evt);
            }
        });

        jLabel4.setText("Radio");

        botonCapturaRadio.setText("Ingresar Valor");
        botonCapturaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCapturaRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout circuloLayout = new javax.swing.GroupLayout(circulo);
        circulo.setLayout(circuloLayout);
        circuloLayout.setHorizontalGroup(
            circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, circuloLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(calcularCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCapturaRadio)
                    .addComponent(campoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
        circuloLayout.setVerticalGroup(
            circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circuloLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCapturaRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcularCirculo)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Círculo", circulo);

        campoBaseRect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoBaseRectFocusGained(evt);
            }
        });
        campoBaseRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBaseRectActionPerformed(evt);
            }
        });

        campoAlturaRect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoAlturaRectFocusGained(evt);
            }
        });
        campoAlturaRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAlturaRectActionPerformed(evt);
            }
        });

        calcularRectagulo.setText("Calcular");
        calcularRectagulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularRectaguloActionPerformed(evt);
            }
        });

        jLabel2.setText("Base");

        jLabel3.setText("Altura");

        ingresarValores.setText("Ingresar Valores");
        ingresarValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarValoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RectanguloLayout = new javax.swing.GroupLayout(Rectangulo);
        Rectangulo.setLayout(RectanguloLayout);
        RectanguloLayout.setHorizontalGroup(
            RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RectanguloLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RectanguloLayout.createSequentialGroup()
                        .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoAlturaRect, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(campoBaseRect)))
                    .addGroup(RectanguloLayout.createSequentialGroup()
                        .addComponent(ingresarValores, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcularRectagulo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        RectanguloLayout.setVerticalGroup(
            RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RectanguloLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBaseRect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAlturaRect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarValores)
                    .addComponent(calcularRectagulo))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Rectángulo", Rectangulo);

        jLabel11.setText("Base");

        jLabel12.setText("Altura");

        campoBaseCuad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoBaseCuadFocusGained(evt);
            }
        });
        campoBaseCuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBaseCuadActionPerformed(evt);
            }
        });

        campoAlturaCuad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoAlturaCuadFocusGained(evt);
            }
        });
        campoAlturaCuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAlturaCuadActionPerformed(evt);
            }
        });

        ingresarValorCuad.setText("Ingresar Valores");
        ingresarValorCuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarValorCuadActionPerformed(evt);
            }
        });

        calcularCuad.setText("Calcular");
        calcularCuad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularCuadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cuadrilateroLayout = new javax.swing.GroupLayout(cuadrilatero);
        cuadrilatero.setLayout(cuadrilateroLayout);
        cuadrilateroLayout.setHorizontalGroup(
            cuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadrilateroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(cuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cuadrilateroLayout.createSequentialGroup()
                        .addGroup(cuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(cuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoAlturaCuad, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(campoBaseCuad)))
                    .addGroup(cuadrilateroLayout.createSequentialGroup()
                        .addComponent(ingresarValorCuad, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcularCuad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        cuadrilateroLayout.setVerticalGroup(
            cuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadrilateroLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(cuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBaseCuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAlturaCuad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cuadrilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarValorCuad)
                    .addComponent(calcularCuad))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuadrilatero", cuadrilatero);

        campoCatMay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCatMayFocusGained(evt);
            }
        });
        campoCatMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCatMayActionPerformed(evt);
            }
        });

        campoCatMen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCatMenFocusGained(evt);
            }
        });
        campoCatMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCatMenActionPerformed(evt);
            }
        });

        calcularTriangulo.setText("Calcular");
        calcularTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularTrianguloActionPerformed(evt);
            }
        });

        jLabel6.setText("Cateto Mayor");

        jLabel7.setText("Cateto Menor");

        jLabel10.setText("Hipotenusa");

        campoHipot.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoHipotFocusGained(evt);
            }
        });

        ingresarValorTriang.setText("Ingresar Valores");
        ingresarValorTriang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarValorTriangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TriangulosLayout = new javax.swing.GroupLayout(Triangulos);
        Triangulos.setLayout(TriangulosLayout);
        TriangulosLayout.setHorizontalGroup(
            TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TriangulosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TriangulosLayout.createSequentialGroup()
                        .addComponent(ingresarValorTriang, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcularTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoCatMay)
                        .addComponent(campoCatMen)
                        .addComponent(campoHipot)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        TriangulosLayout.setVerticalGroup(
            TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TriangulosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCatMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCatMen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoHipot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TriangulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularTriangulo)
                    .addComponent(ingresarValorTriang))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Triángulo Recto", Triangulos);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("Resultado");

        campoResultado.setColumns(20);
        campoResultado.setRows(5);
        jScrollPane1.setViewportView(campoResultado);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("Calculadora de Figuras Geométricas: Área & Perímetro");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCatMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCatMenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCatMenActionPerformed

    private void campoCatMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCatMayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCatMayActionPerformed

    private void campoBaseRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBaseRectActionPerformed
       campoBaseRect.setBackground(Color.white);
       campoBaseRect.setText("");
    }//GEN-LAST:event_campoBaseRectActionPerformed

    private void botonCapturaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCapturaRadioActionPerformed
       
        try{
            circulo1.setRadio(Double.valueOf(campoRadio.getText()));
            campoResultado.setText("Radio: " + circulo1.getRadio());
        }catch(java.lang.NumberFormatException error){
            campoRadio.setBackground(Color.yellow);
            campoRadio.setVisible(rootPaneCheckingEnabled);
            campoRadio.setText("Ingrese un valor");
        }

    }//GEN-LAST:event_botonCapturaRadioActionPerformed

    private void calcularCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularCirculoActionPerformed
        campoResultado.setText("Área: " + circulo1.calcularArea()+ "\n"+
                "Perímetro: " + circulo1.calcularPerimetro());
        
    }//GEN-LAST:event_calcularCirculoActionPerformed

    private void calcularTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularTrianguloActionPerformed
        campoResultado.setText("Área: " + triangulo.calcularArea()+ "\n"+
                "Perímetro: " + triangulo.calcularPerimetro());
        
    }//GEN-LAST:event_calcularTrianguloActionPerformed

    private void campoRadioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRadioFocusGained
        campoRadio.setBackground(Color.white);
        campoRadio.setText("");
    }//GEN-LAST:event_campoRadioFocusGained

    private void calcularRectaguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularRectaguloActionPerformed
    campoResultado.setText("Área: " + rectangulo.calcularArea()+ "\n"+
                "Perímetro: " + rectangulo.calcularPerimetro());
    }//GEN-LAST:event_calcularRectaguloActionPerformed

    private void campoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRadioActionPerformed

    private void ingresarValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarValoresActionPerformed
        try{
            rectangulo.setBase(Double.valueOf(campoBaseRect.getText()));
            campoResultado.setText("Base: " + rectangulo.getBase()+ "\n"+
            "Altura: " + rectangulo.getAltura());
             rectangulo.setAltura(Double.valueOf(campoAlturaRect.getText()));
           
        }catch(java.lang.NumberFormatException error){
            campoBaseRect.setBackground(Color.yellow);
            campoBaseRect.setText("Ingrese un valor");
            campoAlturaRect.setBackground(Color.yellow);
            campoAlturaRect.setText("Ingrese un valor");
        }
    }//GEN-LAST:event_ingresarValoresActionPerformed

    private void campoAlturaRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAlturaRectActionPerformed
        campoAlturaRect.setBackground(Color.white);
        campoAlturaRect.setText("");
    }//GEN-LAST:event_campoAlturaRectActionPerformed

    private void campoBaseRectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoBaseRectFocusGained
        campoBaseRect.setBackground(Color.white);
        campoBaseRect.setText("");
    }//GEN-LAST:event_campoBaseRectFocusGained

    private void campoAlturaRectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoAlturaRectFocusGained
        campoAlturaRect.setBackground(Color.white);
        campoAlturaRect.setText("");
    }//GEN-LAST:event_campoAlturaRectFocusGained

    private void campoBaseCuadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoBaseCuadFocusGained
        campoBaseCuad.setBackground(Color.white);
        campoBaseCuad.setText("");
    }//GEN-LAST:event_campoBaseCuadFocusGained

    private void campoBaseCuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBaseCuadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBaseCuadActionPerformed

    private void campoAlturaCuadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoAlturaCuadFocusGained
        campoAlturaCuad.setBackground(Color.white);
        campoAlturaCuad.setText("");
    }//GEN-LAST:event_campoAlturaCuadFocusGained

    private void campoAlturaCuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAlturaCuadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAlturaCuadActionPerformed

    private void ingresarValorCuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarValorCuadActionPerformed
         try{
            cuadrado.setBase(Double.valueOf(campoBaseCuad.getText()));
            cuadrado.setAltura(Double.valueOf(campoAlturaCuad.getText()));
            campoResultado.setText("Base: " + cuadrado.getBase()+ "\n"+
                    "Altura: " + cuadrado.getAltura());
        }catch(java.lang.NumberFormatException error){
            campoBaseCuad.setBackground(Color.yellow);
            campoBaseCuad.setText("Ingrese un valor");
            campoAlturaCuad.setBackground(Color.yellow);
            campoAlturaCuad.setText("Ingrese un valor");
        }
    }//GEN-LAST:event_ingresarValorCuadActionPerformed

    private void calcularCuadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularCuadActionPerformed
        campoResultado.setText("Área: " + cuadrado.calcularArea()+ "\n"+
                "Perímetro: " + cuadrado.calcularPerimetro());
    }//GEN-LAST:event_calcularCuadActionPerformed

    private void ingresarValorTriangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarValorTriangActionPerformed
         try{
            triangulo.setCatMay(Double.valueOf(campoCatMay.getText())); 
            triangulo.setCatMen(Double.valueOf(campoCatMen.getText()));
            triangulo.setHipotenusa(Double.valueOf(campoHipot.getText()));
            campoResultado.setText("Cateto Mayor: " + triangulo.getCatMay()+ "\n"+
                    "Cateto Menor: " + triangulo.getCatMen()+ "\n"+
                    "Hipotenusa: " + triangulo.getHipotenusa()
            );
            
        }catch(java.lang.NumberFormatException error){
            campoCatMay.setBackground(Color.yellow);
            campoCatMay.setText("Ingrese un valor");
            campoCatMen.setBackground(Color.yellow);
            campoCatMen.setText("Ingrese un valor");
            campoHipot.setBackground(Color.yellow);
            campoHipot.setText("Ingrese un valor");
        }
        
    }//GEN-LAST:event_ingresarValorTriangActionPerformed

    private void campoCatMayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCatMayFocusGained
        campoCatMay.setBackground(Color.white);
        campoCatMay.setText("");
    }//GEN-LAST:event_campoCatMayFocusGained

    private void campoCatMenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCatMenFocusGained
        campoCatMen.setBackground(Color.white);
        campoCatMen.setText("");
    }//GEN-LAST:event_campoCatMenFocusGained

    private void campoHipotFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoHipotFocusGained
        campoHipot.setBackground(Color.white);
        campoHipot.setText("");
    }//GEN-LAST:event_campoHipotFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Rectangulo;
    private javax.swing.JPanel Triangulos;
    private javax.swing.JButton botonCapturaRadio;
    private javax.swing.JButton calcularCirculo;
    private javax.swing.JButton calcularCuad;
    private javax.swing.JButton calcularRectagulo;
    private javax.swing.JButton calcularTriangulo;
    private javax.swing.JTextField campoAlturaCuad;
    private javax.swing.JTextField campoAlturaRect;
    private javax.swing.JTextField campoBaseCuad;
    private javax.swing.JTextField campoBaseRect;
    private javax.swing.JTextField campoCatMay;
    private javax.swing.JTextField campoCatMen;
    private javax.swing.JTextField campoHipot;
    private javax.swing.JTextField campoRadio;
    private javax.swing.JTextArea campoResultado;
    private javax.swing.JPanel circulo;
    private javax.swing.JPanel cuadrilatero;
    private javax.swing.JButton ingresarValorCuad;
    private javax.swing.JButton ingresarValorTriang;
    private javax.swing.JButton ingresarValores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
/*
 * AUTHOR: SOFIA NOVAK
 * DATE: 26/09/17
*/
